name: gorestan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:

  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.18
  provider: ^6.1.2
  google_maps_flutter: ^2.0.6
  location: ^8.0.0 
  webview_flutter: ^4.10.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
